//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Keyword
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please type in a image url")]
        public string Picture { get; set; }
        [Required(ErrorMessage = "Please enter an exercise name")]
        public string Exercise { get; set; }
        [Required(ErrorMessage = "Please enter some instructions")]
        public string Instructions { get; set; }
        [Required(ErrorMessage = "Please enter a body part")]
        public string BodyPart { get; set; }
        public int Blike { get; set; }
        public int Bdislike { get; set; }
    }
}
